#!/usr/bin/env python3
"""
Build a few STATIC homepage concept variants (bone_v3-<theme>) so Will can feel the
recommendations before we touch the canonical homepage. Each is a self-contained page in
docs/design/homepage/ (reuses the bone design system + the local demo/Tahoe assets that
build_preview.py copies there).

Concepts lean into Will's steer: signal "Pacer AI works IN Claude", ICP = CROs/RevOps (who
use Claude), and drop the LinkedIn-ish "we read 30 job postings" framing.

Run:  python3 scripts/build_preview.py   (once, to place local demo assets)
      python3 scripts/build_concepts.py
      python3 scripts/build_preview.py --serve   (then open the printed /bone_v3-*.html URLs)
"""
import os, re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "docs/design/homepage")
SRC = open(os.path.join(REPO, "src/homepage/index-build.html")).read()
JS = open(os.path.join(REPO, "src/wpcode/footer.js")).read()

def block(start, end="</section>"):
    i = SRC.find(start)
    if i < 0: raise SystemExit(f"not found: {start}")
    j = SRC.find(end, i) + len(end)
    return SRC[i:j]

BASE_CSS = re.search(r"<style>(.*?)</style>", SRC, re.DOTALL).group(1)

# --- reused components (extracted; no nested same-tag so slicing is safe) ---
PROOF   = block('<section class="proof">')
SHOWCASE_RAW = block('<section class="showcase-wrap"')
HOW     = block('<section class="how"')
CASES   = block('<section class="band" data-section="case-studies">')
INTEG   = block('<section class="band" data-section="integrations">')
SECURITY= block('<section class="band" data-section="security">')
FAQ     = block('<section class="band" data-section="frequently-asked-questions">')
CTA     = block('<section class="cta"')
FOOTER  = block('<footer>', '</footer>')
NAV     = block('<nav>', '</nav>')

# demo -> local asset + a caption (my rec: label the showcase)
SHOWCASE = (SHOWCASE_RAW
    .replace("https://pacer-demo-worker.will-078.workers.dev/", "demo-video-by-claude.html")
    .replace("https://getpacerai.com/wp-content/uploads/2026/07/tahoe-bg.jpg", "tahoe-bg.jpg")
    .replace("</section>", '<p class="demo-cap">Pacer AI planning a number — live in Claude.</p></section>'))

STEPS = ('<div class="wrap"><p class="steps"><b>Ask in Claude</b> &nbsp;&rarr;&nbsp; '
         '<b>Reconciled model</b> &nbsp;&rarr;&nbsp; <b>Board slide + workbook</b> &nbsp;&rarr;&nbsp; '
         '<b>On-pace tracking</b></p></div>')

TILES = ('<div class="wrap"><section class="tiles">'
  '<div class="tile"><h3>Deterministic</h3><p>Not a slide &mdash; a model. Same numbers every run, generated by the Pacer engine, never improvised.</p></div>'
  '<div class="tile"><h3>Reconciled to reported revenue</h3><p>ARR, retention, and the waterfall tie to the source financials &mdash; diligence-grade, not directional.</p></div>'
  '<div class="tile"><h3>Board-grade, in Claude</h3><p>Target plan, account waterfall, and by-market build render inline; the full workbook is one click away.</p></div>'
  '</section></div>')

# --- reframed / improved sections (shared across variants) ---
USECASES = ('<section class="band" data-section="use-cases">'
  '<div class="eyebrow">Use Cases</div>'
  '<h2>The revenue questions you can finally just ask</h2>'
  '<p class="lede">Type the question in Claude. Pacer AI answers with a reconciled model &mdash; tied to Finance, not a guess.</p>'
  '<div class="usecases">'
  '<div class="uc"><h3>&ldquo;What&rsquo;s my real ARR &mdash; and why doesn&rsquo;t it match the CRM?&rdquo;</h3><p>One reconciled number, tied to Finance to the dollar, with the movement bridge behind it.</p></div>'
  '<div class="uc"><h3>&ldquo;Where is revenue leaking, and which accounts?&rdquo;</h3><p>New, expansion, contraction, and churn at the account-product grain &mdash; the whitespace and the risk.</p></div>'
  '<div class="uc"><h3>&ldquo;Can we hit the number &mdash; and what has to be true?&rdquo;</h3><p>A bottoms-up plan: pipeline, coverage, capacity, and headcount sized to the target.</p></div>'
  '<div class="uc"><h3>&ldquo;Build me the board slide.&rdquo;</h3><p>The ARR waterfall and pace-to-plan render inline in Claude; the workbook is one click away.</p></div>'
  '</div></section>')

TEAM = ('<section class="band" data-section="team">'
  '<div class="eyebrow">Team</div>'
  '<h2>Built by the people who ran the diligence</h2>'
  '<div class="team-lead">'
  '<img class="team-photo" src="https://getpacerai.com/wp-content/uploads/2026/04/will-sullivan-headshot.jpeg" alt="Will Sullivan">'
  '<div><p class="team-note">Founded by an operator turned M&amp;A advisor &mdash; <b>Will Sullivan</b>, a former PwC M&amp;A advisor, search fund operator, and West Point graduate.</p>'
  '<div class="chips"><span>Ex-PwC TMT M&amp;A</span><span>West Point</span><span>$25B+ diligence</span></div></div></div>'
  '<div class="advisors"><div class="adv-label">Backed by an advisory bench</div>'
  '<div class="adv-row"><span>Veach.AI &mdash; QoE</span><span>Weighbridge &mdash; Tech DD</span><span>Inside Consulting</span><span>Charlie Mike &mdash; RevOps</span><span>Modern Revenue</span></div></div>'
  '<a class="team-link" href="/team/">Meet the full team &amp; advisory network &rarr;</a></section>')

PRICING = ('<section class="band" data-section="pricing">'
  '<div class="eyebrow">Pricing</div>'
  '<h2>Aligned to your revenue, not your seat count</h2>'
  '<p class="lede">No seat licenses. No per-user fees. Pacer AI is priced to the value it manages &mdash; when your revenue grows, so does the engagement.</p>'
  '<div class="price-steps">'
  '<div class="pstep"><b>1 &middot; Diagnostic</b><span>A reconciled read on your ARR and where it&rsquo;s leaking.</span></div>'
  '<div class="pstep"><b>2 &middot; Data Cube</b><span>CRM, billing, and ERP unified into one M&amp;A-grade model.</span></div>'
  '<div class="pstep"><b>3 &middot; Ongoing</b><span>Board-grade reporting, refreshed daily, live in Claude and Excel.</span></div>'
  '</div><a class="cta-inline" href="https://calendly.com/pacerai/strategy-session">Discuss Pricing</a></section>')

BIZCASE = ('<section class="band" data-section="value">'
  '<div class="eyebrow">The business case</div>'
  '<h2>Board-grade revenue intelligence, at a fraction of the cost</h2>'
  '<div class="value-tiles">'
  '<div class="vtile"><div class="vk">Lower cost</div><h3>Replaces a $1M+ data team</h3><p>One engagement stands in for a data team, a BI stack, and Big 4 QoR fees &mdash; &ldquo;a million dollars and 12 months,&rdquo; per one CFO.</p></div>'
  '<div class="vtile"><div class="vk">Higher return</div><h3>A fraction of a Big 4 QoR</h3><p>Diligence-grade ARR analysis for a fraction of the $200&ndash;600K a buy-side Quality of Revenue engagement runs.</p></div>'
  '<div class="vtile"><div class="vk">Faster</div><h3>Days, not months</h3><p>From kickoff to a reconciled model in days &mdash; then refreshed daily, not rebuilt quarterly.</p></div>'
  '</div></section>')

NEW_CSS = """
#pacerai-homepage .demo-cap{max-width:var(--maxw);margin:12px auto 0;padding:0 24px;text-align:center;font-size:13px;color:var(--muted)}
#pacerai-homepage .team-lead{display:flex;gap:22px;align-items:center;margin-top:22px;flex-wrap:wrap}
#pacerai-homepage .team-photo{width:96px;height:96px;border-radius:50%;object-fit:cover;border:1px solid var(--line)}
#pacerai-homepage .chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}
#pacerai-homepage .chips span{font-size:12px;font-weight:700;color:var(--navy);background:var(--card);border:1px solid var(--line);border-radius:100px;padding:5px 12px}
#pacerai-homepage .advisors{margin-top:26px;border-top:1px solid var(--line);padding-top:20px}
#pacerai-homepage .adv-label{font-size:11px;letter-spacing:1.4px;text-transform:uppercase;color:var(--kick);font-weight:700;margin-bottom:12px}
#pacerai-homepage .adv-row{display:flex;gap:10px;flex-wrap:wrap}
#pacerai-homepage .adv-row span{font-size:13px;font-weight:600;color:var(--ink-mid);background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:8px 14px}
#pacerai-homepage .price-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:24px}
#pacerai-homepage .pstep{border:1px solid var(--line);border-radius:14px;background:var(--surface);padding:20px}
#pacerai-homepage .pstep b{display:block;color:var(--navy);font-size:15px;margin-bottom:6px}
#pacerai-homepage .pstep span{font-size:14px;color:#5a5648;line-height:1.5}
#pacerai-homepage .hero h1 .lede-teal{color:var(--teal)}
@media(max-width:900px){#pacerai-homepage .price-steps{grid-template-columns:1fr}#pacerai-homepage .team-lead{flex-direction:column;align-items:flex-start}}
"""

# --- variant heroes + phrases + section order ---
COMMON = dict(nav=NAV, proof=PROOF, showcase=SHOWCASE, steps=STEPS, how=HOW, tiles=TILES,
              usecases=USECASES, cases=CASES, bizcase=BIZCASE, integ=INTEG, security=SECURITY,
              team=TEAM, pricing=PRICING, faq=FAQ, cta=CTA)

def hero(kick, h1, sub):
    return (f'<section class="hero" data-section="top"><div class="kick">{kick}</div>'
            f'<h1>{h1}</h1><p class="hero-sub">{sub}</p></section>')

VARIANTS = {
  "claude-native": dict(
    phrases=['a reconciled model','an ARR waterfall','a board-ready slide','your real ARR'],
    hero=hero("Runs in Claude",
      'Ask Claude a revenue question.<br>Pacer AI answers with <span class="for-rotor"><span class="rotor">a reconciled model</span></span>',
      'The Revenue Modeling Agent for CROs &amp; RevOps &mdash; live in Claude, reconciled to Finance, refreshed daily.'),
    order=['showcase','steps','how','usecases','cases','bizcase','integ','security','team','pricing','faq','cta']),
  "agent-outcome": dict(
    phrases=['minutes','one session','Claude','Excel'],
    hero=hero("Revenue Modeling Agent",
      'The agent that builds your number.<br>Reconciled to Finance, in <span class="for-rotor"><span class="rotor">minutes</span></span>',
      'Pacer AI turns your CRM, billing, and ERP into a board-grade ARR model &mdash; in Claude, in Excel, or as a live dashboard.'),
    order=['bizcase','showcase','how','usecases','cases','integ','security','team','pricing','faq','cta']),
  "problem-tiebreak": dict(
    phrases=['ends the tiebreak','ties out to the dollar','settles it in Claude'],
    hero=hero("For CROs &amp; RevOps",
      'Your CRM says one ARR number.<br>Finance says another.<br><span class="lede-teal">Pacer AI <span class="rotor">ends the tiebreak</span>.</span>',
      'A reconciled revenue model your board can trust &mdash; built in Claude, tied to Finance to the dollar.'),
    order=['showcase','how','usecases','cases','bizcase','integ','security','team','pricing','faq','cta']),
}

HEAD = ('<!doctype html><html lang="en"><head><meta charset="utf-8">'
  '<meta name="viewport" content="width=device-width,initial-scale=1">'
  '<title>Pacer AI &mdash; concept: {name}</title>'
  '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
  '<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700;800&family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet"></head><body>')

for name, v in VARIANTS.items():
    body = "".join(COMMON[k] for k in v["order"])
    # swap the rotor phrase array (footer.js section 6) for this variant
    js = re.sub(r"var phrases\s*=\s*\[[^\]]*\];",
                "var phrases = [" + ", ".join("'" + p + "'" for p in v["phrases"]) + "];",
                JS, count=1)
    doc = (HEAD.format(name=name)
           + f"<style>{BASE_CSS}{NEW_CSS}</style>"
           + '<div id="pacerai-homepage">' + NAV + v["hero"] + body + FOOTER + '</div>'
           + f"<script>{js}</script></body></html>")
    p = os.path.join(OUT, f"bone_v3-{name}.html")
    open(p, "w").write(doc)
    print(f"  bone_v3-{name}.html  ({len(doc)} chars, order: {', '.join(v['order'])})")

print("\nDone. Serve with: python3 scripts/build_preview.py --serve")
